Repository CMPUT301W23T14/QRHunter-App, pull requests merged in 2023-03, with the labels that each got.

#54 Feature/qr code scoring
  .gitignore
  QRHunter/app/build.gradle
  QRHunter/app/src/main/java/com/example/qrhunter/data/model/QRCode.java
  QRHunter/app/src/main/java/com/example/qrhunter/utils/QRCodeUtil.java
  QRHunter/app/src/test/java/com/example/qrhunter/ExampleUnitTest.java
  QRHunter/app/src/test/java/com/example/qrhunter/QRCodeUtilTest.java
Labels: user-story, feature

#59 Feature/map display
  QRHunter/app/build.gradle
  QRHunter/app/src/main/AndroidManifest.xml
  QRHunter/app/src/main/java/com/example/qrhunter/ui/map/MapFragment.java
  QRHunter/app/src/main/res/layout/fragment_map.xml
  QRHunter/app/src/main/res/values-night/themes.xml
  QRHunter/build.gradle
Labels: feature

#80 Feat/lb search players
  QRHunter/.idea/deploymentTargetDropDown.xml
  QRHunter/app/src/main/java/com/example/qrhunter/ui/leaderboard/LeaderboardAdapter.java
  QRHunter/app/src/main/java/com/example/qrhunter/ui/leaderboard/LeaderboardFragment.java
  QRHunter/app/src/main/java/com/example/qrhunter/ui/leaderboard/LeaderboardViewModel.java
  QRHunter/app/src/main/res/drawable/placement_first.xml
  QRHunter/app/src/main/res/drawable/placement_second.xml
  QRHunter/app/src/main/res/drawable/placement_third.xml
  QRHunter/app/src/main/res/layout/fragment_leaderboard_players.xml
Labels: feature

#81 Feature/markers
  QRHunter/app/src/main/java/com/example/qrhunter/data/model/Location.java
  QRHunter/app/src/main/java/com/example/qrhunter/data/repository/QRCodeRepository.java
  QRHunter/app/src/main/java/com/example/qrhunter/ui/map/MapFragment.java
  QRHunter/app/src/main/java/com/example/qrhunter/ui/map/MapViewModel.java
Labels: feature

#92 Geolocation Bug Fix
  QRHunter/app/src/main/java/com/example/qrhunter/data/repository/QRCodeRepository.java
  QRHunter/app/src/main/java/com/example/qrhunter/ui/scan/ScanViewModel.java
Labels: bug
